/**
 * Color Profiles for PeopleConnect Mobile
 * These match the admin portal's color profile definitions
 */

export interface ColorProfile {
  id: string;
  name: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  gradientStart: string;
  gradientEnd: string;
}

export const COLOR_PROFILES: Record<string, ColorProfile> = {
  whisprr: {
    id: 'whisprr',
    name: 'Whisprr',
    description: 'Purple & Teal gradient - Default brand theme',
    primaryColor: '#7C3AED',
    secondaryColor: '#2DD4BF',
    gradientStart: '#7C3AED',
    gradientEnd: '#2DD4BF',
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean Blue',
    description: 'Blue & Cyan - Professional and calm',
    primaryColor: '#3B82F6',
    secondaryColor: '#06B6D4',
    gradientStart: '#3B82F6',
    gradientEnd: '#06B6D4',
  },
  forest: {
    id: 'forest',
    name: 'Forest Green',
    description: 'Green & Teal - Natural and refreshing',
    primaryColor: '#16A34A',
    secondaryColor: '#0D9488',
    gradientStart: '#16A34A',
    gradientEnd: '#0D9488',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Orange',
    description: 'Orange & Pink - Warm and energetic',
    primaryColor: '#F97316',
    secondaryColor: '#EC4899',
    gradientStart: '#F97316',
    gradientEnd: '#EC4899',
  },
  rose: {
    id: 'rose',
    name: 'Rose Gold',
    description: 'Rose & Gold - Elegant and sophisticated',
    primaryColor: '#F43F5E',
    secondaryColor: '#F59E0B',
    gradientStart: '#F43F5E',
    gradientEnd: '#F59E0B',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Indigo & Purple - Deep and modern',
    primaryColor: '#6366F1',
    secondaryColor: '#A855F7',
    gradientStart: '#6366F1',
    gradientEnd: '#A855F7',
  },
  navypink: {
    id: 'navypink',
    name: 'Navy Pink',
    description: 'Navy Blue & Pink - Professional yet vibrant',
    primaryColor: '#1e3a5f',
    secondaryColor: '#ec4899',
    gradientStart: '#1e3a5f',
    gradientEnd: '#ec4899',
  },
  bluepink: {
    id: 'bluepink',
    name: 'Blue Pink',
    description: 'Blue & Pink - Fresh and playful',
    primaryColor: '#3b82f6',
    secondaryColor: '#ec4899',
    gradientStart: '#3b82f6',
    gradientEnd: '#ec4899',
  },
  bluegradient: {
    id: 'bluegradient',
    name: 'Blue Gradient',
    description: 'Blue tones - Clean and professional',
    primaryColor: '#0066cc',
    secondaryColor: '#00a3cc',
    gradientStart: '#0066cc',
    gradientEnd: '#00a3cc',
  },
  charcoal: {
    id: 'charcoal',
    name: 'Charcoal',
    description: 'Dark gray tones - Sleek and modern',
    primaryColor: '#374151',
    secondaryColor: '#6B7280',
    gradientStart: '#1F2937',
    gradientEnd: '#4B5563',
  },
  blackgold: {
    id: 'blackgold',
    name: 'Black Gold',
    description: 'Black & Gold - Luxurious and elegant',
    primaryColor: '#1F2937',
    secondaryColor: '#F59E0B',
    gradientStart: '#111827',
    gradientEnd: '#F59E0B',
  },
  roseember: {
    id: 'roseember',
    name: 'Rose Ember',
    description: 'Rose & Ember - Warm and passionate',
    primaryColor: '#BE185D',
    secondaryColor: '#DC2626',
    gradientStart: '#BE185D',
    gradientEnd: '#DC2626',
  },
  darkindigo: {
    id: 'darkindigo',
    name: 'Dark Indigo',
    description: 'Deep indigo - Mysterious and refined',
    primaryColor: '#312E81',
    secondaryColor: '#4338CA',
    gradientStart: '#1E1B4B',
    gradientEnd: '#4338CA',
  },
  blackorange: {
    id: 'blackorange',
    name: 'Black Orange',
    description: 'Black & Orange - Bold and energetic',
    primaryColor: '#1F2937',
    secondaryColor: '#EA580C',
    gradientStart: '#111827',
    gradientEnd: '#EA580C',
  },
  navyorange: {
    id: 'navyorange',
    name: 'Navy Orange',
    description: 'Navy & Orange - Classic with flair',
    primaryColor: '#1e3a5f',
    secondaryColor: '#f97316',
    gradientStart: '#1e3a5f',
    gradientEnd: '#f97316',
  },
  navysilver: {
    id: 'navysilver',
    name: 'Navy Silver',
    description: 'Navy & Silver - Professional elegance',
    primaryColor: '#1e3a5f',
    secondaryColor: '#94a3b8',
    gradientStart: '#1e3a5f',
    gradientEnd: '#94a3b8',
  },
  sunsetoasis: {
    id: 'sunsetoasis',
    name: 'Sunset Oasis',
    description: 'Golden orange and teal oasis vibes',
    primaryColor: '#FF6F20',
    secondaryColor: '#009B77',
    gradientStart: '#FF6F20',
    gradientEnd: '#009B77',
  },
  tropicalbreeze: {
    id: 'tropicalbreeze',
    name: 'Tropical Breeze',
    description: 'Warm orange and golden tropical feel',
    primaryColor: '#FF8C00',
    secondaryColor: '#FFD700',
    gradientStart: '#FF8C00',
    gradientEnd: '#FFD700',
  },
  coralreef: {
    id: 'coralreef',
    name: 'Coral Reef',
    description: 'Coral pink and ocean teal',
    primaryColor: '#FF7F50',
    secondaryColor: '#20B2AA',
    gradientStart: '#FF7F50',
    gradientEnd: '#20B2AA',
  },
  citrussplash: {
    id: 'citrussplash',
    name: 'Citrus Splash',
    description: 'Bright lemon and lime freshness',
    primaryColor: '#FFD700',
    secondaryColor: '#32CD32',
    gradientStart: '#FFD700',
    gradientEnd: '#32CD32',
  },
  forestfire: {
    id: 'forestfire',
    name: 'Forest Fire',
    description: 'Fiery orange and forest green',
    primaryColor: '#FF4500',
    secondaryColor: '#2E8B57',
    gradientStart: '#FF4500',
    gradientEnd: '#2E8B57',
  },
  oceansunset: {
    id: 'oceansunset',
    name: 'Ocean Sunset',
    description: 'Sunset orange over ocean blue',
    primaryColor: '#FF8C00',
    secondaryColor: '#00CED1',
    gradientStart: '#FF8C00',
    gradientEnd: '#1E90FF',
  },
  autumnharvest: {
    id: 'autumnharvest',
    name: 'Autumn Harvest',
    description: 'Rich autumn orange and forest green',
    primaryColor: '#D2691E',
    secondaryColor: '#3CB371',
    gradientStart: '#FF8C00',
    gradientEnd: '#8B0000',
  },
  mintysunrise: {
    id: 'mintysunrise',
    name: 'Minty Sunrise',
    description: 'Fresh mint and warm sunrise',
    primaryColor: '#20B2AA',
    secondaryColor: '#FFA500',
    gradientStart: '#20B2AA',
    gradientEnd: '#FFA500',
  },
  junglevibes: {
    id: 'junglevibes',
    name: 'Jungle Vibes',
    description: 'Lush green jungle energy',
    primaryColor: '#32CD32',
    secondaryColor: '#5F9EA0',
    gradientStart: '#32CD32',
    gradientEnd: '#5F9EA0',
  },
  tranquiltides: {
    id: 'tranquiltides',
    name: 'Tranquil Tides',
    description: 'Calm navy and soft aqua',
    primaryColor: '#1A3E5D',
    secondaryColor: '#A1D6E2',
    gradientStart: '#1A3E5D',
    gradientEnd: '#A1D6E2',
  },
  deepseamystique: {
    id: 'deepseamystique',
    name: 'Deep Sea Mystique',
    description: 'Deep navy and vibrant teal',
    primaryColor: '#003B5C',
    secondaryColor: '#00B2A9',
    gradientStart: '#003B5C',
    gradientEnd: '#00B2A9',
  },
  sereneshores: {
    id: 'sereneshores',
    name: 'Serene Shores',
    description: 'Soft aqua and pristine white',
    primaryColor: '#A4D7E1',
    secondaryColor: '#4A90A4',
    gradientStart: '#4A90A4',
    gradientEnd: '#A4D7E1',
  },
  oceandepths: {
    id: 'oceandepths',
    name: 'Ocean Depths',
    description: 'Deep teal and light aqua',
    primaryColor: '#002D32',
    secondaryColor: '#A7E3E0',
    gradientStart: '#002D32',
    gradientEnd: '#A7E3E0',
  },
  aquadream: {
    id: 'aquadream',
    name: 'Aqua Dream',
    description: 'Dreamy teal and soft white',
    primaryColor: '#009B77',
    secondaryColor: '#A7E3E0',
    gradientStart: '#009B77',
    gradientEnd: '#A7E3E0',
  },
  wavecrest: {
    id: 'wavecrest',
    name: 'Wave Crest',
    description: 'Deep teal to vibrant aqua',
    primaryColor: '#005F73',
    secondaryColor: '#00B2A9',
    gradientStart: '#005F73',
    gradientEnd: '#00B2A9',
  },
  nauticalnights: {
    id: 'nauticalnights',
    name: 'Nautical Nights',
    description: 'Deep navy and coral accents',
    primaryColor: '#1A1A2E',
    secondaryColor: '#E94560',
    gradientStart: '#1A1A2E',
    gradientEnd: '#E94560',
  },
  celestialwaves: {
    id: 'celestialwaves',
    name: 'Celestial Waves',
    description: 'Navy blue and celestial aqua',
    primaryColor: '#1A3E5D',
    secondaryColor: '#A1D6E2',
    gradientStart: '#0F2439',
    gradientEnd: '#A1D6E2',
  },
  senateblue: {
    id: 'senateblue',
    name: 'Senate Blue',
    description: 'Roman senate deep blue',
    primaryColor: '#003366',
    secondaryColor: '#007FFF',
    gradientStart: '#003366',
    gradientEnd: '#1E90FF',
  },
  marblewhite: {
    id: 'marblewhite',
    name: 'Marble White',
    description: 'Classic Roman marble elegance',
    primaryColor: '#4A4A4A',
    secondaryColor: '#C0C0C0',
    gradientStart: '#E8E8E8',
    gradientEnd: '#A0A0A0',
  },
  colosseumstone: {
    id: 'colosseumstone',
    name: 'Colosseum Stone',
    description: 'Ancient stone gray tones',
    primaryColor: '#6B6B6B',
    secondaryColor: '#BEBEBE',
    gradientStart: '#4B4B4B',
    gradientEnd: '#BEBEBE',
  },
  triumphpurple: {
    id: 'triumphpurple',
    name: 'Triumph Purple',
    description: 'Imperial triumphant purple',
    primaryColor: '#6A0DAD',
    secondaryColor: '#9B59B6',
    gradientStart: '#6A0DAD',
    gradientEnd: '#9B59B6',
  },
  rusticterracotta: {
    id: 'rusticterracotta',
    name: 'Rustic Terracotta',
    description: 'Warm terracotta earth tones',
    primaryColor: '#E07B53',
    secondaryColor: '#DEB887',
    gradientStart: '#E07B53',
    gradientEnd: '#F4A460',
  },
  imperialviolet: {
    id: 'imperialviolet',
    name: 'Imperial Violet',
    description: 'Royal violet gradients',
    primaryColor: '#8A2BE2',
    secondaryColor: '#D8BFD8',
    gradientStart: '#8A2BE2',
    gradientEnd: '#D8BFD8',
  },
  savannasunset: {
    id: 'savannasunset',
    name: 'Savanna Sunset',
    description: 'African savanna golden sunset',
    primaryColor: '#E4923A',
    secondaryColor: '#8B4513',
    gradientStart: '#E4923A',
    gradientEnd: '#8B4513',
  },
  junglecanopy: {
    id: 'junglecanopy',
    name: 'Jungle Canopy',
    description: 'Dense jungle green canopy',
    primaryColor: '#228B22',
    secondaryColor: '#006400',
    gradientStart: '#228B22',
    gradientEnd: '#2F4F2F',
  },
  desertdunes: {
    id: 'desertdunes',
    name: 'Desert Dunes',
    description: 'Sandy desert warm tones',
    primaryColor: '#E4B65D',
    secondaryColor: '#C19A6B',
    gradientStart: '#E4B65D',
    gradientEnd: '#C19A6B',
  },
  riverbankreflections: {
    id: 'riverbankreflections',
    name: 'Riverbank Reflections',
    description: 'Calm river blues and navy',
    primaryColor: '#4682B4',
    secondaryColor: '#1E3A5F',
    gradientStart: '#4682B4',
    gradientEnd: '#1E3A5F',
  },
  mountainmajesty: {
    id: 'mountainmajesty',
    name: 'Mountain Majesty',
    description: 'Majestic mountain greens',
    primaryColor: '#556B2F',
    secondaryColor: '#A8B400',
    gradientStart: '#2A3D00',
    gradientEnd: '#A8B400',
  },
  nightsafari: {
    id: 'nightsafari',
    name: 'Night Safari',
    description: 'Nocturnal safari dark tones',
    primaryColor: '#2C2C2C',
    secondaryColor: '#708090',
    gradientStart: '#1C1C1C',
    gradientEnd: '#4A4A4A',
  },
  tropicaloasis: {
    id: 'tropicaloasis',
    name: 'Tropical Oasis',
    description: 'Vibrant tropical coral and pink',
    primaryColor: '#FF6F61',
    secondaryColor: '#FF4C00',
    gradientStart: '#FF6F61',
    gradientEnd: '#FF4C00',
  },
  earthytones: {
    id: 'earthytones',
    name: 'Earthy Tones',
    description: 'Natural earth brown palette',
    primaryColor: '#A67C2D',
    secondaryColor: '#C2B280',
    gradientStart: '#A67C2D',
    gradientEnd: '#C2B280',
  },
  safarisand: {
    id: 'safarisand',
    name: 'Safari Sand',
    description: 'Warm safari sand colors',
    primaryColor: '#C4A35A',
    secondaryColor: '#E8CBA8',
    gradientStart: '#A68B6D',
    gradientEnd: '#E8CBA8',
  },
  forestfloor: {
    id: 'forestfloor',
    name: 'Forest Floor',
    description: 'Deep forest browns and beige',
    primaryColor: '#4E3B31',
    secondaryColor: '#D9CBA0',
    gradientStart: '#4E3B31',
    gradientEnd: '#8B7355',
  },
  sunsetoverwater: {
    id: 'sunsetoverwater',
    name: 'Sunset Over Water',
    description: 'Warm sunset reflecting on water',
    primaryColor: '#FF6F61',
    secondaryColor: '#FFCC00',
    gradientStart: '#FF6F61',
    gradientEnd: '#FFCC00',
  },
};

export const DEFAULT_COLOR_PROFILE = 'whisprr';

export function getColorProfile(profileId: string): ColorProfile {
  return COLOR_PROFILES[profileId] || COLOR_PROFILES[DEFAULT_COLOR_PROFILE];
}

export default COLOR_PROFILES;
